Args = --initialize-at-run-time=com.clickhouse.client \
  --initialize-at-run-time=com.clickhouse.jdbc \
  --initialize-at-run-time=com.clickhouse.data \
  --initialize-at-run-time=com.clickhouse.config
